### ISSUE TITLE
似乎是控制台对中文的支持不够好？

### ISSUE THREAD

**Issue by LiuJiewenTT** [Waheal/Minecraft-Server-Launcher#14]
情景一：
服务器控制处的编码必须要用“输入编码：UTF8”和“输出编码：ANSI”的组合才能使来自和显示在日志与游戏内的中文信息都得到正确显示。
![image](https://github.com/Waheal/Minecraft-Server-Launcher/assets/43092274/b411d418-8de6-4f76-96fc-a72a4fbce9c2)

情景二：
server.properties中不能包含中文，比如level-name和motd。设置完保存了看起来一切正常没有变成\u什么的，但是启动过游戏中文就都变\u之类的了。
![image](https://github.com/Waheal/Minecraft-Server-Launcher/assets/43092274/6ec31031-1926-4dcf-bc43-cb3cc4bc7ad5)

**Comment by LiuJiewenTT** [comment]
``` csharp 
item001.Text = File.ReadAllText(serverbase + @"\server.properties");
```
要不设定`encoding`参数为utf8试试？反正不用中文的话gbk2312和ASCII没啥区别。
我在隔壁MCSL2也遇到了这个问题，都是一启动服务器这里的编码就变成这样了。那边选择直接设定读文件编码来修复了。

**Comment by Waheal** [comment]
我记得原版motd就是不支持中文（好像是？
后续版本可能会考虑加入配置文件更换编码的功能（目前的配置文件修改功能只是个毛胚房，能用就行QwQ

**Comment by Waheal** [comment]
对于你说的情景一的问题，是由Java版本和服务端共同决定的，我测试过多次，有的版本需要输入输出均为UTF8，有的版本需要输入UTF8输出ANSI，情况复杂，所以最好的处理方式就是先将输出编码和输入编码均设置为UTF8，若服务器在运行后输出乱码日志，MSL再进行提示进行更改编码。
