### ISSUE TITLE
希望在修改服务器存放目录时考虑到更名的情况

### ISSUE THREAD

**Issue by LiuJiewenTT** [Waheal/Minecraft-Server-Launcher#15]
现行方案是做移动处理，这会导致通过"mklink /J"和"mklink /D"链接的内容被影响。两者被移动后都会变成普通文件夹，并且源目录的内容被移动，这不那么地安全。（这对于仅仅是重命名文件夹而言是完全可用避免的）希望能借鉴Windows系统的资源管理器在“剪贴”这一操作的行为，对于两者的联结或目录符号链接不移动并使新目录为空普通目录（希望此时提供警告或实现联结或链接的重建）

如果可以的话，还希望能添加对于链接的检测，能够应对由“mklink /D”创建的“目录符号链接”就很棒了。
![image](https://github.com/Waheal/Minecraft-Server-Launcher/assets/43092274/a43054f8-70d8-458e-9fb4-ce7afc47f335)

**Comment by LiuJiewenTT** [comment]
（给自己讲迷糊了）主要期望：支持更名目录而非全部当作移动处理。

**Comment by Waheal** [comment]
此问题不好解，cs如果要更名最优解决方案也是移动文件夹
对于你说的链接检测，后续版本可能会加入
