### ISSUE TITLE
新版本的服务器无法多开（无报错）

### ISSUE THREAD

**Issue by Yuyi-Oak** [Waheal/Minecraft-Server-Launcher#21]
当开启一个服务器后想要开启另一个服务器时点击开启无反应

**Comment by luluxiaoyu** [comment]
问题已复现：先启动id为1的服务器窗口后，id为0的服务器窗口无法启动，其他情况未知  
BUG定位：服务器ID和运行状态的检测ID产生冲突，导致误认为某ID服务器已经开启

**Comment by luluxiaoyu** [comment]
Fixed v3.5.4.9
