### ISSUE TITLE
bug: 服务器窗口被隐藏后无法再次打开，并且会造成服务端残留后台

### ISSUE THREAD

**Issue by wockkk** [Waheal/Minecraft-Server-Launcher#26]
![无标题](https://github.com/MSLTeam/MSL/assets/157705747/0dec2a8f-c271-44f5-be1e-815c7052f967)
只能通过双击服务器图标来进入隐藏之前的服务器页面
如果通过点击“服务器设置”进入就会像图片一样
![image](https://github.com/MSLTeam/MSL/assets/157705747/ccda503a-0779-44b7-9fa8-67797aa68ea3)
很无语

**Comment by luluxiaoyu** [comment]
像图片一样指的是无法进行任何操作，只能看吗

**Comment by luluxiaoyu** [comment]
已确认： 服务器窗口被隐藏后无法再次打开，服务器列表显示为未运行（但服务器仍在正常运行）并且会造成服务端残留后台

**Comment by Waheal** [comment]
v3.5.5.1版本已修复
