### ISSUE TITLE
[Feat]: 将arclight服务端中支持的forge版本拓宽（即将每个arclight服务端中所下载的Forge版本增加为2种）

### ISSUE THREAD

**Issue by Yuyi-Oak** [Waheal/Minecraft-Server-Launcher#27]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我提交的功能请求没有人提交过.
- [x] 我认为这个功能是可以实现的，是对大部分人有用的.

### 描述功能

现在arclighr下载的forge版本为固定的，当遇到mod所需forge版本更高时需要手动更改文件，希望将新版本中的msl所下载的forge版本增加到两个比较热门的forge版本

### 实现方法

手动更改.jar文件中的配置信息

**Comment by luluxiaoyu** [comment]
大部分人用不到此功能，暂无计划支持。
