### ISSUE TITLE
[Feat]: 支持Bungeecord开服和更多的服务端

### ISSUE THREAD

**Issue by Yuyi-Oak** [Waheal/Minecraft-Server-Launcher#28]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我提交的功能请求没有人提交过.
- [X] 我认为这个功能是可以实现的，是对大部分人有用的.

### 描述功能

希望支持Bungeecord服务端和更多的服务端来提升更好的体验

**Comment by luluxiaoyu** [comment]
使用人数不多，但是以后会支持的（记入小本本.jpg）

**Comment by Yuyi-Oak** [comment]
s属性大爆发！
Sleep！
