### ISSUE TITLE
[Bug]: 特殊情况下服务器列表出现重复

### ISSUE THREAD

**Issue by Yuyi-Oak** [Waheal/Minecraft-Server-Launcher#29]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我已经安装了[.net framework 4.7.2运行环境](https://www.mslmc.cn/docs/start.html).
- [X] 我确认我提交的问题没有人提交过.

### 描述 Bug

在某些特殊情况下时，服务器列表出现重复项

### 如何复现BUG？

Windows版本：windows server 2019
1.在服务器设置中更换服务端且不保存
2.开启服务端
3.BUG复现完成

### Windows版本

Other

**Comment by luluxiaoyu** [comment]
无法复现 若无法提供更多信息 issue将关闭

**Comment by luluxiaoyu** [comment]
issue closed.
If u can provide more information, pls feedback here，thanks！

**Comment by Waheal** [comment]
[v3.5.5.5](https://github.com/MSLTeam/MSL/commit/a462fce0cc86262c7d3e6e5ff849ef561af5659d)已修复
