### ISSUE TITLE
[Bug]: 不能启用自动启动服务器

### ISSUE THREAD

**Issue by wockkk** [Waheal/Minecraft-Server-Launcher#30]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我已经安装了[.net framework 4.7.2运行环境](https://www.mslmc.cn/docs/start.html).
- [X] 我确认我提交的问题没有人提交过.

### 描述 Bug

不能启用自动启动服务器

### 如何复现BUG？

https://github.com/MSLTeam/MSL/assets/157705747/c61c354d-c599-437f-81c2-6b5de315b231

看视频↑

### Windows版本

Windows 10

**Comment by Waheal** [comment]
v3.5.5.6已修复
