### ISSUE TITLE
[Bug]: 开启软件后无法自动打开服务端

### ISSUE THREAD

**Issue by Yuyi-Oak** [Waheal/Minecraft-Server-Launcher#31]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我已经安装了[.net framework 4.7.2运行环境](https://www.mslmc.cn/docs/start.html).
- [X] 我确认我提交的问题没有人提交过.

### 描述 Bug

请看VCR

### 如何复现BUG？

请看VCR

### Windows版本

Windows Server 2019

**Comment by luluxiaoyu** [comment]
https://github.com/MSLTeam/MSL/assets/58876608/7d238338-9540-44f6-a61b-a0ecb9e4d55e

**Comment by Waheal** [comment]
亲测无此bug，观看视频我发现您没有打开开关
![image](https://github.com/MSLTeam/MSL/assets/77955152/e0cbab56-7b3a-4514-85e6-19b47d11af6e)
