### ISSUE TITLE
[Feat]: Java扫描优化

### ISSUE THREAD

**Issue by luluxiaoyu** [Waheal/Minecraft-Server-Launcher#32]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我提交的功能请求没有人提交过.
- [X] 我认为这个功能是可以实现的，是对大部分人有用的.

### 描述功能

深度扫描Java中途应当可以取消，在设置界面允许预扫描、开服器应当记住历史上玩家选择过的JAVA并校验是否依然有效  

by 

海波_Hiber
QQ 2166227840

### 实现方法

提供一个思路，扫描路径树，JAVA目录结构很有特征的

**Comment by Waheal** [comment]
您好，扫描路径树就是简单扫描模式使用的思路  
![image](https://github.com/MSLTeam/MSL/assets/77955152/af88c89a-336d-4372-a435-90a0c2d3db0e)
关于扫描可打断这部分，我们会尝试进行更改，以及扫描后的Java存储到config中，也会进行修改，敬请期待后续版本更新

**Comment by Waheal** [comment]
取消扫描功能暂无计划，其余功能均已加入，此ISSUE关闭
