### ISSUE TITLE
[Feat]: UI:更新布局

### ISSUE THREAD

**Issue by luluxiaoyu** [Waheal/Minecraft-Server-Launcher#33]
### 检查

- [x] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我提交的功能请求没有人提交过.
- [X] 我认为这个功能是可以实现的，是对大部分人有用的.

### 描述功能

UI更新：所有border逐步换成hc的card

### 实现方法

换掉就好

**Comment by Waheal** [comment]
不想换了！关闭！
