### ISSUE TITLE
[Feat]: 申请接入第三方FRP:樱花frp

### ISSUE THREAD

**Issue by tanyuanwen** [Waheal/Minecraft-Server-Launcher#35]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我提交的功能请求没有人提交过.
- [X] 我认为这个功能是可以实现的，是对大部分人有用的.

### 描述功能

feature

**Comment by luluxiaoyu** [comment]
apidoc: https://api.natfrp.com/docs/#/

**Comment by luluxiaoyu** [comment]
已完成
