### ISSUE TITLE
[Feat]: 移除关闭正版验证提示

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Waheal/Minecraft-Server-Launcher#37]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我提交的功能请求没有人提交过.
- [X] 我认为这个功能是可以实现的，是对大部分人有用的.

### 描述功能

feature 在设置中加入一个选项并设为默认不显示该提示
原因：大多数服主都知道正版验证相关事项，无需烦人的提示

**Comment by Waheal** [comment]
豪德

**Comment by Waheal** [comment]
我们不会默认关闭此提示，但是会在设置中加入关闭此提示的开关

**Comment by Waheal** [comment]
[v3.5.8.8](https://github.com/MSLTeam/MSL/releases/tag/v3.5.8.8) 已更新
