### ISSUE TITLE
[Feat]: 可以使用MSL来控制另一台使用MSL开服的服务器，既远程控制

### ISSUE THREAD

**Issue by Yuyi-Oak** [Waheal/Minecraft-Server-Launcher#44]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我提交的功能请求没有人提交过.
- [X] 我认为这个功能是可以实现的，是对大部分人有用的.

### 描述功能

当我使用MSL在一台远程服务器开服时，我可以通过在我本地电脑打开的MSL实现远程控制

**Comment by Waheal** [comment]
😋😋😋

**Comment by Yuyi-Oak** [comment]
屎山豪赤

**Comment by Waheal** [comment]
此功能在MSL项目中暂无计划，后续可能会和一些后端面板联动（如teapanel），此ISSUE关闭
