### ISSUE TITLE
[Bug]: 伪终端输出过多导致无法显示

### ISSUE THREAD

**Issue by TGBUG** [Waheal/Minecraft-Server-Launcher#48]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我已经安装了[.net framework 4.7.2运行环境](https://www.mslmc.cn/docs/start.html).
- [X] 我确认我提交的问题没有人提交过.

### 描述 Bug

当伪终端需要显示过多的信息时，关闭再打开伪终端就会出现什么也不显示的情况（包括右下角的“关服”以及“隐藏终端”按钮），关闭服务器窗口再次打开也无法解决

### 如何复现BUG？

1. 开启服务器很长时间or发送很多控制台信息
2. 关闭伪终端
3. 再次开启伪终端

### Windows版本

Windows Server 2022

**Comment by luluxiaoyu** [comment]
请先暂时关闭伪终端，先用着普通版本的控制台叭

**Comment by Waheal** [comment]
最新版已支持手动清屏功能，对于日志无法显示的问题，已另有人提出issue #56 ，我们会持续跟进，此issue先行关闭
