### ISSUE TITLE
[Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭

### ISSUE THREAD

**Issue by GongSunFangYun** [Waheal/Minecraft-Server-Launcher#52]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我已经安装了[.net framework 4.7.2运行环境](https://www.mslmc.cn/docs/start.html).
- [X] 我确认我提交的问题没有人提交过.

### 描述 Bug

我在使用伪终端的时候，按下Ctrl+C关闭服务器。实际上服务器已经关闭，但是MSL界面还是会显示服务器正在关闭
我一直点关服(双击强制关服也测试了)没什么用，一直提示正在关闭
![屏幕截图 2024-10-07 170148](https://github.com/user-attachments/assets/9cbb02f7-5147-4b51-a734-5e2fc0afd2b2)
还有一种方式触发该bug，就是频繁的强制关服，这同样会导致MSL卡在关闭服务器提示但是服务器已关闭
![image](https://github.com/user-attachments/assets/4f732f44-9c69-4fb8-9cff-bb95a43bdea7)
顺便一提，如果在该状态下尝试关闭MSL服务器管理窗口，会弹出该提示(因为MSL认为你没有关闭服务器)：
![image](https://github.com/user-attachments/assets/454477a4-7a49-4205-a2e8-371c981d0244)
并且同时服务器列表也会显示服务器正在运行
![image](https://github.com/user-attachments/assets/32ba9ec9-2dc9-40f3-87ad-41ef3349b0e5)

### 如何复现BUG？

第一种方法：使用伪终端多次正常开服并使用Ctrl+C关服，有概率出现该bug
第二种方法：使用伪终端多次正常开服但是每次都强制关服，大概率出现该bug

### Windows版本

Windows 11

**Comment by Waheal** [comment]
请补充说明您的系统环境、使用的Java环境和服务端核心（如不涉及隐私，可截图“服务器设置”界面）
以方便我们进行核实

**Comment by GongSunFangYun** [comment]
设备：Windows11
Java：JDK21（拥有环境变量）
服务器核心：Nukkit-MOT
服务器版本：1.21.20

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/07/2024 22:07 |
| To | MSLTeam/MSL ***@***.***> |
| Cc | IPlayForPlayer ***@***.***>,
Author ***@***.***> |
| Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) |

请补充说明您的系统环境、使用的Java环境和服务端核心（如不涉及隐私，可截图“服务器设置”界面）
以方便我们进行核实

**Comment by Waheal** [comment]
MSL的伪终端功能似乎是没有Ctrl+C关闭进程的功能的，请尝试使用最新版，查看是否还存在此问题
若依旧存在，请联系我们：QQ：2035582067

**Comment by GongSunFangYun** [comment]
但是我确确实实使用Ctrl+C关闭了服务器

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/15/2024 22:44 |
| To | MSLTeam/MSL ***@***.***> |
| Cc | IPlayForPlayer ***@***.***>,
Author ***@***.***> |
| Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) |

MSL的伪终端功能似乎是没有Ctrl+C关闭进程的功能的，请尝试使用最新版，查看是否还存在此问题
若依旧存在，请联系我们：QQ：2035582067

**Comment by Waheal** [comment]
> 但是我确确实实使用Ctrl+C关闭了服务器
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 10/15/2024 22:44 | | To | MSLTeam/MSL ***@***.***> | | Cc | IPlayForPlayer ***@***.***>, Author ***@***.***> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | MSL的伪终端功能似乎是没有Ctrl+C关闭进程的功能的，请尝试使用最新版，查看是否还存在此问题 若依旧存在，请联系我们：QQ：2035582067 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

您好，经测试，我发现您使用的“Nukkit-MOT”端确实有CTRL+C关服功能，不过在最新版本下，我并未复现您所述的关服后依旧显示运行中的bug，请问您在最新版本下还有遇到这个问题吗？

**Comment by GongSunFangYun** [comment]
是的，我在最新的3.6.2.6版本使用Ctrl+C仍然可以关服，这是特意安排的还是说这是个bug？

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2024 22:21 |
| To | MSLTeam/MSL ***@***.***> |
| Cc | IPlayForPlayer ***@***.***>,
Author ***@***.***> |
| Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) |

但是我确确实实使用Ctrl+C关闭了服务器
…
---- Replied Message ---- | From | @.> | | Date | 10/15/2024 22:44 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | MSL的伪终端功能似乎是没有Ctrl+C关闭进程的功能的，请尝试使用最新版，查看是否还存在此问题 若依旧存在，请联系我们：QQ：2035582067 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

您好，经测试，我发现您使用的“Nukkit-MOT”端确实有CTRL+C关服功能，不过在最新版本下，我并未复现您所述的关服后依旧显示运行中的bug，请问您在最新版本下还有遇到这个问题吗？

**Comment by Waheal** [comment]
> 是的，我在最新的3.6.2.6版本使用Ctrl+C仍然可以关服，这是特意安排的还是说这是个bug？
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 10/18/2024 22:21 | | To | MSLTeam/MSL ***@***.***> | | Cc | IPlayForPlayer ***@***.***>, Author ***@***.***> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | 但是我确确实实使用Ctrl+C关闭了服务器 … ---- Replied Message ---- | From | @.> | | Date | 10/15/2024 22:44 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | MSL的伪终端功能似乎是没有Ctrl+C关闭进程的功能的，请尝试使用最新版，查看是否还存在此问题 若依旧存在，请联系我们：QQ：2035582067 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> 您好，经测试，我发现您使用的“Nukkit-MOT”端确实有CTRL+C关服功能，不过在最新版本下，我并未复现您所述的关服后依旧显示运行中的bug，请问您在最新版本下还有遇到这个问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我上面已经说了，CTRL+C关服是您所使用的“Nukkit-MOT”端的特性，与开服器无关
目前我想知道的是，在最新版本下，您所说的“关服后依旧显示服务器未关闭的bug”是否还存在？

**Comment by GongSunFangYun** [comment]
嘶，这个关服特性不只是mot，我刚才在paper上测试了ctrl+c也可以关服

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2024 22:27 |
| To | MSLTeam/MSL ***@***.***> |
| Cc | IPlayForPlayer ***@***.***>,
Author ***@***.***> |
| Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) |

是的，我在最新的3.6.2.6版本使用Ctrl+C仍然可以关服，这是特意安排的还是说这是个bug？
…
---- Replied Message ---- | From | @.> | | Date | 10/18/2024 22:21 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | 但是我确确实实使用Ctrl+C关闭了服务器 … ---- Replied Message ---- | From | @.> | | Date | 10/15/2024 22:44 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | MSL的伪终端功能似乎是没有Ctrl+C关闭进程的功能的，请尝试使用最新版，查看是否还存在此问题 若依旧存在，请联系我们：QQ：2035582067 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> 您好，经测试，我发现您使用的“Nukkit-MOT”端确实有CTRL+C关服功能，不过在最新版本下，我并未复现您所述的关服后依旧显示运行中的bug，请问您在最新版本下还有遇到这个问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

我上面已经说了，CTRL+C关服是您所使用的“Nukkit-MOT”端的特性，与开服器无关
目前我想知道的是，在最新版本下，您所说的“关服后依旧显示服务器未关闭的bug”是否还存在？

**Comment by GongSunFangYun** [comment]
然后就是这个无法正常关服的bug出现概率挺小的。如果出现了我会第一时间提交issues

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2024 22:27 |
| To | MSLTeam/MSL ***@***.***> |
| Cc | IPlayForPlayer ***@***.***>,
Author ***@***.***> |
| Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) |

是的，我在最新的3.6.2.6版本使用Ctrl+C仍然可以关服，这是特意安排的还是说这是个bug？
…
---- Replied Message ---- | From | @.> | | Date | 10/18/2024 22:21 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | 但是我确确实实使用Ctrl+C关闭了服务器 … ---- Replied Message ---- | From | @.> | | Date | 10/15/2024 22:44 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | MSL的伪终端功能似乎是没有Ctrl+C关闭进程的功能的，请尝试使用最新版，查看是否还存在此问题 若依旧存在，请联系我们：QQ：2035582067 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> 您好，经测试，我发现您使用的“Nukkit-MOT”端确实有CTRL+C关服功能，不过在最新版本下，我并未复现您所述的关服后依旧显示运行中的bug，请问您在最新版本下还有遇到这个问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

我上面已经说了，CTRL+C关服是您所使用的“Nukkit-MOT”端的特性，与开服器无关
目前我想知道的是，在最新版本下，您所说的“关服后依旧显示服务器未关闭的bug”是否还存在？

**Comment by GongSunFangYun** [comment]
spigot也测试了，同样也可以ctrl+c关服

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2024 22:27 |
| To | MSLTeam/MSL ***@***.***> |
| Cc | IPlayForPlayer ***@***.***>,
Author ***@***.***> |
| Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) |

是的，我在最新的3.6.2.6版本使用Ctrl+C仍然可以关服，这是特意安排的还是说这是个bug？
…
---- Replied Message ---- | From | @.> | | Date | 10/18/2024 22:21 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | 但是我确确实实使用Ctrl+C关闭了服务器 … ---- Replied Message ---- | From | @.> | | Date | 10/15/2024 22:44 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | MSL的伪终端功能似乎是没有Ctrl+C关闭进程的功能的，请尝试使用最新版，查看是否还存在此问题 若依旧存在，请联系我们：QQ：2035582067 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> 您好，经测试，我发现您使用的“Nukkit-MOT”端确实有CTRL+C关服功能，不过在最新版本下，我并未复现您所述的关服后依旧显示运行中的bug，请问您在最新版本下还有遇到这个问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

我上面已经说了，CTRL+C关服是您所使用的“Nukkit-MOT”端的特性，与开服器无关
目前我想知道的是，在最新版本下，您所说的“关服后依旧显示服务器未关闭的bug”是否还存在？

**Comment by Waheal** [comment]
哦我测试的是低版本（paper1.8.8），如果高版本可以使用CTRL C的话，可能还有Java版本的因素

**Comment by GongSunFangYun** [comment]
所以我觉得这还是开服器本身的问题，而不是核心，不然这么多版本的核心不可能会出现同一个bug

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2024 22:27 |
| To | MSLTeam/MSL ***@***.***> |
| Cc | IPlayForPlayer ***@***.***>,
Author ***@***.***> |
| Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) |

是的，我在最新的3.6.2.6版本使用Ctrl+C仍然可以关服，这是特意安排的还是说这是个bug？
…
---- Replied Message ---- | From | @.> | | Date | 10/18/2024 22:21 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | 但是我确确实实使用Ctrl+C关闭了服务器 … ---- Replied Message ---- | From | @.> | | Date | 10/15/2024 22:44 | | To | MSLTeam/MSL @.> | | Cc | IPlayForPlayer @.>, Author @.> | | Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) | MSL的伪终端功能似乎是没有Ctrl+C关闭进程的功能的，请尝试使用最新版，查看是否还存在此问题 若依旧存在，请联系我们：QQ：2035582067 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> 您好，经测试，我发现您使用的“Nukkit-MOT”端确实有CTRL+C关服功能，不过在最新版本下，我并未复现您所述的关服后依旧显示运行中的bug，请问您在最新版本下还有遇到这个问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

我上面已经说了，CTRL+C关服是您所使用的“Nukkit-MOT”端的特性，与开服器无关
目前我想知道的是，在最新版本下，您所说的“关服后依旧显示服务器未关闭的bug”是否还存在？

**Comment by Waheal** [comment]
CTRL C关服和输入stop关服本身逻辑一致，并不是造成开服器一直显示“服务器运行中”的因素（或主要因素）
如果关服后MSL依旧显示服务器在运行，可能是软件判断失误，我记得有次代码提交修过这个问题，不确定现行版本还是否存在了

既然您现在暂未复现此问题，那本ISSUE先行关闭，如果以后又遇到此问题，可以重新开一个ISSUE（在复现此问题后，您也可以打开任务管理器查看MC服务器进程是否有残留，即后台是否存在java.exe进程，并一并反馈给我们）

**Comment by GongSunFangYun** [comment]
好的，谢谢

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2024 22:38 |
| To | MSLTeam/MSL ***@***.***> |
| Cc | IPlayForPlayer ***@***.***>,
Author ***@***.***> |
| Subject | Re: [MSLTeam/MSL] [Bug]伪终端有的时候使用Ctrl+C快捷键关闭服务器并不能正常关闭 (Issue #52) |

CTRL C关服和输入stop关服本身逻辑一致，并不是造成开服器一直显示“服务器运行中”的因素（或主要因素）
如果关服后MSL依旧显示服务器在运行，可能是软件判断失误，我记得有次代码提交修过这个问题，不确定现行版本还是否存在了

既然您现在暂未复现此问题，那本ISSUE先行关闭，如果以后又遇到此问题，可以重新开一个ISSUE（在复现此问题后，您也可以打开任务管理器查看MC服务器进程是否有残留，即后台是否存在java.exe进程，并一并反馈给我们）

**Comment by GongSunFangYun** [comment]
package cn.f208.prs;


import cn.nukkit.Player;
import cn.nukkit.command.Command;
import cn.nukkit.command.CommandSender;
import cn.nukkit.plugin.PluginBase;
import cn.nukkit.utils.TextFormat;
import cn.nukkit.form.window.FormWindowCustom;
import cn.nukkit.form.window.FormWindowSimple;
import cn.nukkit.form.element.ElementDropdown;
import cn.nukkit.form.element.ElementInput;
import cn.nukkit.event.Listener;
import cn.nukkit.event.player.PlayerFormRespondedEvent;
import cn.nukkit.event.EventHandler;


import java.text.SimpleDateFormat;
import java.util.*;


public class ReportPlayer extends PluginBase implements Listener {


    private final List<Report> reports = new ArrayList<>(); // 保存所有举报记录


    @Override
    public void onEnable() {
        this.getServer().getPluginManager().registerEvents(this, this);
        this.getLogger().info(TextFormat.GREEN + "ReportPlayer plugin enabled");
    }


    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (command.getName().equalsIgnoreCase("report")) {
            if (sender instanceof Player) {
                Player player = (Player) sender;
                if (args.length > 0) {
                    String partialName = args[0];
                    Player matchedPlayer = findPlayerByPartialName(partialName);
                    if (matchedPlayer != null) {
                        openReasonWindow(player, matchedPlayer.getName());
                    } else {
                        player.sendMessage("§cThis player isn't online.");
                    }
                } else {
                    openReportWindow(player);
                }
            } else {
                sender.sendMessage(TextFormat.RED + "This command can only be used by players.");
            }
            return true;
        } else if (command.getName().equalsIgnoreCase("managereport")) {
            if (sender instanceof Player) {
                Player player = (Player) sender;
                if (player.hasPermission("reportmanager.use") || player.isOp()) {
                    openManageReportWindow(player);
                } else {
                    player.sendMessage(TextFormat.RED + "You don't have permission to use this command.");
                }
            }
            return true;
        }
        return false;
    }


    private Player findPlayerByPartialName(String partialName) {
        for (Player p : this.getServer().getOnlinePlayers().values()) {
            if (p.getName().toLowerCase().startsWith(partialName.toLowerCase())) {
                return p;
            }
        }
        return null;
    }


    private void openReportWindow(Player player) {
        FormWindowCustom form = new FormWindowCustom("Report Player");
        List<String> playerNames = new ArrayList<>();
        for (Player p : this.getServer().getOnlinePlayers().values()) {
            playerNames.add(p.getName());
        }
        form.addElement(new ElementDropdown("Select a player to report", playerNames));
        player.showFormWindow(form, 1);
    }


    private void openReasonWindow(Player player, String reportedPlayerName) {
        FormWindowCustom form = new FormWindowCustom("Report | " + reportedPlayerName);
        form.addElement(new ElementInput("Reason", "Enter your reason here..."));
        List<String> proofOptions = new ArrayList<>();
        proofOptions.add("Yes");
        proofOptions.add("No");
        form.addElement(new ElementDropdown("Do you have proof?", proofOptions));
        player.showFormWindow(form, 2);
    }


    private void openManageReportWindow(Player player) {
        FormWindowSimple manageWindow = new FormWindowSimple("Manage Report", "Select a report to view details:");
        SimpleDateFormat sdf = new SimpleDateFormat("yy.MM.dd HH:mm:ss");
        for (int i = 0; i < reports.size(); i++) {
            Report report = reports.get(i);
            manageWindow.addButton(new cn.nukkit.form.element.ElementButton("Report-" + (i + 1) + " [" + sdf.format(report.getReportTime()) + "]"));
        }
        player.showFormWindow(manageWindow, 3);
    }


    private void openReportDetailsWindow(Player player, Report report) {
        FormWindowSimple detailWindow = new FormWindowSimple("Report Details",
                "Report Target: " + report.getTargetPlayer() + "\n" +
                        "Report Source: " + report.getSourcePlayer() + "\n" +
                        "Report Reason: " + report.getReason() + "\n" +
                        "Report Time: " + new SimpleDateFormat("yy.MM.dd HH:mm:ss").format(report.getReportTime())
        );
        detailWindow.addButton(new cn.nukkit.form.element.ElementButton("Start Processing"));
        detailWindow.addButton(new cn.nukkit.form.element.ElementButton("Ignore"));
        player.showFormWindow(detailWindow, 4);
    }


    @EventHandler
    public void onFormResponded(PlayerFormRespondedEvent event) {
        Player player = event.getPlayer();
        if (event.getWindow() instanceof FormWindowCustom) {
            FormWindowCustom window = (FormWindowCustom) event.getWindow();
            FormResponseCustom response = (FormResponseCustom) event.getResponse();
            if (event.getFormID() == 1) {
                // 选择举报目标玩家
                int selectedIndex = response.getDropdownResponse(0).getElementID();
                String reportedPlayerName = this.getServer().getOnlinePlayers().values().toArray(new Player[0])[selectedIndex].getName();
                openReasonWindow(player, reportedPlayerName);
            } else if (event.getFormID() == 2) {
                // 填写举报的原因
                String reason = response.getInputResponse(0);
                String proof = response.getDropdownResponse(1).getElementContent();
                String reportedPlayerName = window.getTitle().split("\\|")[1].trim();
                Report newReport = new Report(reportedPlayerName, player.getName(), reason, new Date());
                reports.add(newReport);
                notifyAdmins();
                player.sendMessage("§aYou have reported " + reportedPlayerName + " for " + reason + ". Proof provided: " + proof);
            }
        } else if (event.getWindow() instanceof FormWindowSimple) {
            FormWindowSimple window = (FormWindowSimple) event.getWindow();
            if (event.getFormID() == 3) {
                // 管理员打开管理窗口时查看所有举报
                int selectedIndex = window.getButtons().indexOf(window.getClickedButton());
                if (selectedIndex >= 0) {
                    Report selectedReport = reports.get(selectedIndex);
                    openReportDetailsWindow(player, selectedReport);
                }
            } else if (event.getFormID() == 4) {
                // 举报详情界面点击按钮
                int buttonIndex = window.getButtons().indexOf(window.getClickedButton());
                if (buttonIndex == 0) { // "Start Processing"
                    player.sendMessage("You have started processing the report.");
                } else if (buttonIndex == 1) { // "Ignore"
                    player.sendMessage("You have ignored the report.");
                }
            }
        }
    }


    private void notifyAdmins() {
        for (Player p : this.getServer().getOnlinePlayers().values()) {
            if (p.hasPermission("reportmanager.use") || p.isOp()) {
                p.sendMessage("§aYou have received a new report!");
                p.sendMessage("Use /managereport to open the report manage panel!");
            }
        }
    }
}
