### ISSUE TITLE
[Feat]: 建议在核心下载列表增加Nukkit分支版本的下载

### ISSUE THREAD

**Issue by GongSunFangYun** [Waheal/Minecraft-Server-Launcher#53]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我提交的功能请求没有人提交过.
- [X] 我认为这个功能是可以实现的，是对大部分人有用的.

### 描述功能

比如Nukkit-MemoryOfTime，Nukkit-PetterM1Edition以及PowerNukkitX(看情况)
原版NukkitX使用的人其实很少，大部分都是使用分支版本开服

### 实现方法

选择后从相关的release中查找最新版本下载

**Comment by luluxiaoyu** [comment]
已向MSLAPI中添加Nukkit-MemoryOfTime，Nukkit-PetterM1Edition的**最新版**下载
老版本服务端后续可能会考虑支持下载
