### ISSUE TITLE
[Bug]: 映射功能中选择ChmlFrp的http映射100%出现异常

### ISSUE THREAD

**Issue by winter0203** [Waheal/Minecraft-Server-Launcher#55]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我已经安装了[.net framework 4.7.2运行环境](https://www.mslmc.cn/docs/start.html).
- [X] 我确认我提交的问题没有人提交过.

### 描述 Bug

客户端映射中创建ChmlFrp的http映射，启动时100%报错，且使用映射网站自带的frp开启无任何异常
例子：启动中，请稍候……
2024/10/09 16:29:17 [I] [root.go:125] 欢迎使用ChmlFrp映射客户端!
2024/10/09 16:29:17 [I] [root.go:135] 从ChmlFrp API获取配置文件...
failed to parse proxy M0ezEOjU, err: custom_domains and subdomain should set at least one of them

### 如何复现BUG？

客户端映射中创建ChmlFrp的http映射并启动，100%复现
![QQ20241009-163242](https://github.com/user-attachments/assets/1db70706-3cc0-4a70-8773-65c038c66d96)
![QQ20241009-163251](https://github.com/user-attachments/assets/c7d031e2-fbc8-4786-9a05-c09e265b6a33)

### Windows版本

Windows 11

**Comment by luluxiaoyu** [comment]
是的 目前仅支持tcp和udp类型 后续会修复

**Comment by luluxiaoyu** [comment]
fixed in 3.6.3.4

**Comment by Armsuki** [comment]
隧道创建api调用失败的原因，及解决方法（HTTP）
