### ISSUE TITLE
[Bug]: 伪终端概率出现开服无日志输出问题

### ISSUE THREAD

**Issue by GongSunFangYun** [Waheal/Minecraft-Server-Launcher#56]
### 检查

- [X] 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
- [X] 我确认我已经安装了[.net framework 4.7.2运行环境](https://www.mslmc.cn/docs/start.html).
- [X] 我确认我提交的问题没有人提交过.

### 描述 Bug

看视频

https://github.com/user-attachments/assets/1ff0952d-1f5f-4342-a049-5b26f94c968e

我的服务器核心：Nukkit-MOT
我的服务器版本：1.21.20
我的服务器JAVA环境：JDK 21.0.4+Java变量环境

### 如何复现BUG？

概率问题，反正用伪终端会有六成出现该问题

### Windows版本

Windows 11

**Comment by Waheal** [comment]
请尝试使用最新版，查看是否还存在此问题
因为我们这边一直无法复现，若您依旧遇到此问题，建议联系我们：QQ：2035582067
