### ISSUE TITLE
在更新时询问用户是否更新

### ISSUE THREAD

**Issue by LiuBinzhe** [Waheal/Minecraft-Server-Launcher#7]
在有新版本时询问用户是否下载，而不是自动下载，这样我就得非常影响使用体验，并在设置里增加“检查更新”按钮。

**Comment by Waheal** [comment]
通知：关于开服器自动更新：
最近，接到许多用户反馈开服器的自动更新很影响使用体验，但如果你不更新，我又没法确保旧版开服器是否有bug，且我也无法在线修复旧版本中的bug，这时，就会有用户进入q群开始询问，说有bug为什么不修复。
以前的开服器是有取消更新的功能的，但由于频频出现上述情况，新版本就给取消了，如果你真的不想更新，就在下载更新的界面点击取消即可，不要再向我反馈取消自动更新的相关问题了。
