### ISSUE TITLE
启动器更新问题

### ISSUE THREAD

**Issue by MochinagaYuna** [Waheal/Minecraft-Server-Launcher#8]
win10系统，自3.5.0.2开始，MSL更新之后再次打开会重复跳更新，关于界面版本号没有发生变化。3.5.0.4更新后MSL无法打开，双击应用程序无任何反应

**Comment by Waheal** [comment]
已收到此类问题反馈，但暂时无法确定问题在哪，请问PCL启动器能在你的系统上正常运行吗？

**Comment by MochinagaYuna** [comment]
> 已收到此类问题反馈，但暂时无法确定问题在哪，请问PCL启动器能在你的系统上正常运行吗？

可以

**Comment by MochinagaYuna** [comment]
> 已收到此类问题反馈，但暂时无法确定问题在哪，请问PCL启动器能在你的系统上正常运行吗？

目前3.5.0.6版本依旧无法运行

**Comment by Waheal** [comment]
加Q：2035582067，需要了解下详细情况
