### ISSUE TITLE
自动开启内网映射

### ISSUE THREAD

**Issue by LBZiXL** [Waheal/Minecraft-Server-Launcher#9]
在映射菜单里增加一个“自动开启”之类的按钮，主要用途是在内网映射出错关闭时自动打开（不过好像有关掉之后再打开就会显示端口占用的bug）

**Comment by Waheal** [comment]
最新版已更新，详情查看开服器设置界面
关于frp无法关闭的问题，这边已经发现，但暂未找到最好的解决方法，后续会持续跟进的

**Comment by Waheal** [comment]
最新版已更新开启软件自动打开frp，你所提的关闭后自动打开frpc暂时无法做到，因为frpc通常不会出现报错关闭的情况，后续我也会持续跟进这个问题的
关于frp无法关闭的问题，这边已经发现，但暂未找到最好的解决方法，后续会持续跟进的
